-- WP-PD01: authored for static review only; NOT EXECUTED.
-- PostgreSQL 18 proposed; installed version must be inspected only after authorization.
-- Run only in a separately authorized dedicated disposable database.
-- Bootstrap must have CREATE ROLE/schema/extension authority and ownership capability.
-- Preexisting names deliberately fail; no IF NOT EXISTS adoption of unknown objects.
-- No business tables, data, ETL, publication functions, login credentials or role memberships.
BEGIN;
SET LOCAL search_path = pg_catalog;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
CREATE ROLE hcb_raw_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_staging_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_curated_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_audit_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_config_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_security_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_reporting_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_extension_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_loader NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_report_reader NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_audit_reader NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE hcb_application_admin NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE SCHEMA raw AUTHORIZATION hcb_raw_owner;
REVOKE ALL ON SCHEMA raw FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_raw_owner IN SCHEMA raw REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_raw_owner IN SCHEMA raw REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_raw_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_raw_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE SCHEMA staging AUTHORIZATION hcb_staging_owner;
REVOKE ALL ON SCHEMA staging FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_staging_owner IN SCHEMA staging REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_staging_owner IN SCHEMA staging REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_staging_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_staging_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE SCHEMA curated AUTHORIZATION hcb_curated_owner;
REVOKE ALL ON SCHEMA curated FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_curated_owner IN SCHEMA curated REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_curated_owner IN SCHEMA curated REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_curated_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_curated_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE SCHEMA audit AUTHORIZATION hcb_audit_owner;
REVOKE ALL ON SCHEMA audit FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_audit_owner IN SCHEMA audit REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_audit_owner IN SCHEMA audit REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_audit_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_audit_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE SCHEMA config AUTHORIZATION hcb_config_owner;
REVOKE ALL ON SCHEMA config FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_config_owner IN SCHEMA config REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_config_owner IN SCHEMA config REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_config_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_config_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE SCHEMA security AUTHORIZATION hcb_security_owner;
REVOKE ALL ON SCHEMA security FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_security_owner IN SCHEMA security REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_security_owner IN SCHEMA security REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_security_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_security_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE SCHEMA reporting AUTHORIZATION hcb_reporting_owner;
REVOKE ALL ON SCHEMA reporting FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_reporting_owner IN SCHEMA reporting REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_reporting_owner IN SCHEMA reporting REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_reporting_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_reporting_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE SCHEMA extensions AUTHORIZATION hcb_extension_owner;
REVOKE ALL ON SCHEMA extensions FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_extension_owner IN SCHEMA extensions REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_extension_owner IN SCHEMA extensions REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_extension_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE hcb_extension_owner REVOKE USAGE ON TYPES FROM PUBLIC;
CREATE EXTENSION btree_gist WITH SCHEMA extensions;
-- No PUBLIC access to extension routines; later exact owner/app grants require review.
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA extensions FROM PUBLIC;
-- Only the migration ledger is created; it is not a banking/business entity.
SET LOCAL ROLE hcb_audit_owner;
CREATE TABLE audit.schema_migration (
    migration_id varchar(128) PRIMARY KEY,
    artifact_sha256 varchar(64) NOT NULL CHECK (artifact_sha256 ~ '^[0-9a-f]{64}$'),
    applied_at timestamptz(6) NOT NULL,
    executor_identity varchar(128) NOT NULL,
    tool_version varchar(128) NOT NULL
);
REVOKE ALL ON TABLE audit.schema_migration FROM PUBLIC;
RESET ROLE;
-- No ledger row is inserted: the future runner records actual successful execution evidence.
-- Application groups intentionally receive no object access or owner membership here.
-- Later migrations must SET ROLE to the intended owner; default privileges are creator-specific.
COMMIT;
